export const RESET_STORE = 'RESET_STORE';


const pieceConstants = {
  GET_ALL_PIECES: {
    REQUEST: 'Piece/GET_ALL_PIECES_REQUEST',
    SUCCESS: 'Piece/GET_ALL_PIECES_SUCCESS',
    FAIL: 'Piece/GET_ALL_PIECES_FAIL',
  },
  GET_ALL_ARTISTS: {
    REQUEST: 'Piece/GET_ALL_ARTISTS_REQUEST',
    SUCCESS: 'Piece/GET_ALL_ARTISTS_SUCCESS',
    FAIL: 'Piece/GET_ALL_ARTISTS_FAIL',
  },
  GET_ALL_GALLERY: {
    REQUEST: 'Piece/GET_ALL_GALLERY_REQUEST',
    SUCCESS: 'Piece/GET_ALL_GALLERY_SUCCESS',
    FAIL: 'Piece/GET_ALL_GALLERY_FAIL',
  },
  GET_PIECE_DETAIL: {
    REQUEST: 'Piece/GET_PIECE_DETAIL_REQUEST',
    SUCCESS: 'Piece/GET_PIECE_DETAIL_SUCCESS',
    FAIL: 'Piece/GET_PIECE_DETAIL_FAIL',
  },
  GET_ARTIST_DETAIL: {
    REQUEST: 'Piece/GET_ARTIST_DETAIL_REQUEST',
    SUCCESS: 'Piece/GET_ARTIST_DETAIL_SUCCESS',
    FAIL: 'Piece/GET_ARTIST_DETAIL_FAIL',
  },
  POST_ARTIST_FAVORITE: {
    REQUEST: 'Piece/POST_ARTIST_FAVORITE_REQUEST',
    SUCCESS: 'Piece/POST_ARTIST_FAVORITE_SUCCESS',
    FAIL: 'Piece/POST_ARTIST_FAVORITE_FAIL',
  },
  POST_EXHIBITION: {
    REQUEST: 'Piece/POST_EXHIBITION_REQUEST',
    SUCCESS: 'Piece/POST_EXHIBITION_SUCCESS',
    FAIL: 'Piece/POST_EXHIBITION_FAIL',
  },
  GET_ARTIST_FAVORITE: {
    REQUEST: 'Piece/GET_ARTIST_FAVORITE_REQUEST',
    SUCCESS: 'Piece/GET_ARTIST_FAVORITE_SUCCESS',
    FAIL: 'Piece/GET_ARTIST_FAVORITE_FAIL',
  }
};

export default pieceConstants
