export const RESET_STORE = 'RESET_STORE';


const galleryConstants = {
  GET_MY_GALLERY_LIST: {
    REQUEST: 'Piece/GET_MY_GALLERY_LIST_REQUEST',
    SUCCESS: 'Piece/GET_MY_GALLERY_LIST_SUCCESS',
    FAIL: 'Piece/GET_MY_GALLERY_LIST_FAIL',
  },
  GET_GALLERY_DETAIL: {
    REQUEST: 'Piece/GET_GALLERY_DETAIL_REQUEST',
    SUCCESS: 'Piece/GET_GALLERY_DETAIL_SUCCESS',
    FAIL: 'Piece/GET_GALLERY_DETAIL_FAIL',
  },
  POST_GALLERY_GROUP: {
    REQUEST: 'Piece/POST_GALLERY_GROUP_REQUEST',
    SUCCESS: 'Piece/POST_GALLERY_GROUP_SUCCESS',
    FAIL: 'Piece/POST_GALLERY_GROUP_FAIL',
  },
  POST_GALLERY_PIECE: {
    REQUEST: 'Piece/POST_GALLERY_PIECE_REQUEST',
    SUCCESS: 'Piece/POST_GALLERY_PIECE_SUCCESS',
    FAIL: 'Piece/POST_GALLERY_PIECE_FAIL',
  },
  UPDATE_GALLERY_GROUP: {
    REQUEST: 'Piece/UPDATE_GALLERY_REQUEST',
    SUCCESS: 'Piece/UPDATE_GALLERY_SUCCESS',
    FAIL: 'Piece/UPDATE_GALLERY_FAIL',
  },
  DELETE_GALLERY_GROUP: {
    REQUEST: 'Piece/DELETE_GALLERY_GROUP_REQUEST',
    SUCCESS: 'Piece/DELETE_GALLERY_GROUP_SUCCESS',
    FAIL: 'Piece/DELETE_GALLERY_GROUP_FAIL',
  },
  DELETE_GALLERY_PIECE: {
    REQUEST: 'Piece/DELETE_GALLERY_PIECE_REQUEST',
    SUCCESS: 'Piece/DELETE_GALLERY_PIECE_SUCCESS',
    FAIL: 'Piece/DELETE_GALLERY_PIECE_FAIL',
  },
};

export default galleryConstants
